rvm: '2.6.0'
cache: bundler
script:
  - mkdir -p spec && bundle exec rspec spec
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake db:seed

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-server-dev-9.3

before_script:
   - psql -c 'create database makersbnb_test;' -U postgres
